// AUTO-GENERATED by scripts/gen-adjacency.mjs — do not edit by hand.
/** Land adjacency between basemap NAME ids (shared border vertices). */
export const ADJACENCY: Record<string, string[]> = {
 "Belgium": [
  "France",
  "Germany",
  "Luxembourg",
  "Netherlands"
 ],
 "France": [
  "Andorra",
  "Belgium",
  "Germany",
  "Italy",
  "Luxembourg",
  "Spain",
  "Switzerland"
 ],
 "Luxembourg": [
  "Belgium",
  "France",
  "Germany"
 ],
 "Germany": [
  "Belgium",
  "Czechoslovakia",
  "Denmark",
  "France",
  "Hungary",
  "Italy",
  "Lithuania",
  "Luxembourg",
  "Netherlands",
  "Poland",
  "Switzerland",
  "Yugoslavia"
 ],
 "Switzerland": [
  "France",
  "Germany",
  "Italy"
 ],
 "Italy": [
  "France",
  "Germany",
  "Switzerland",
  "Yugoslavia"
 ],
 "Spain": [
  "Andorra",
  "France",
  "Portugal"
 ],
 "Andorra": [
  "France",
  "Spain"
 ],
 "Portugal": [
  "Spain"
 ],
 "Ireland": [
  "United Kingdom"
 ],
 "United Kingdom": [
  "Ireland"
 ],
 "Bhutan": [
  "British Raj",
  "Tibet"
 ],
 "Tibet": [
  "Bhutan",
  "British Raj",
  "Chinese warlords",
  "Nepal",
  "Xinjiang"
 ],
 "British Raj": [
  "Afghanistan",
  "Bhutan",
  "Chinese warlords",
  "Iran",
  "Laos",
  "Nepal",
  "Siam",
  "Tibet",
  "Xinjiang"
 ],
 "Qatar": [
  "Emirate of Bin Shal'an",
  "Saudi Arabia",
  "Trucial Oman"
 ],
 "Trucial Oman": [
  "Emirate of Bin Shal'an",
  "India",
  "Muscat and Oman",
  "Oman (British Raj)",
  "Qatar",
  "Saudi Arabia"
 ],
 "Emirate of Bin Shal'an": [
  "Hail",
  "Hejaz",
  "Kuwait",
  "Mesopotamia (GB)",
  "Muscat and Oman",
  "Oman (British Raj)",
  "Qatar",
  "Saudi Arabia",
  "Trucial Oman",
  "Yemen",
  "Yemen (UK)"
 ],
 "Saudi Arabia": [
  "Emirate of Bin Shal'an",
  "Hejaz",
  "Jordan",
  "Kuwait",
  "Mesopotamia (GB)",
  "Muscat and Oman",
  "Oman (British Raj)",
  "Qatar",
  "Trucial Oman",
  "Yemen",
  "Yemen (UK)"
 ],
 "India": [
  "Muscat and Oman",
  "Trucial Oman"
 ],
 "Muscat and Oman": [
  "Emirate of Bin Shal'an",
  "India",
  "Oman (British Raj)",
  "Saudi Arabia",
  "Trucial Oman",
  "Yemen",
  "Yemen (UK)"
 ],
 "Oman (British Raj)": [
  "Emirate of Bin Shal'an",
  "Muscat and Oman",
  "Saudi Arabia",
  "Trucial Oman",
  "Yemen",
  "Yemen (UK)"
 ],
 "Cambodia": [
  "Cochin China",
  "French Indo-China",
  "Laos",
  "Siam"
 ],
 "Laos": [
  "British Raj",
  "Cambodia",
  "Chinese warlords",
  "French Indo-China",
  "Siam"
 ],
 "Siam": [
  "British Raj",
  "Cambodia",
  "Laos",
  "Malaysia"
 ],
 "Chinese warlords": [
  "British Raj",
  "Empire of Japan",
  "French Indo-China",
  "Laos",
  "Mongolia",
  "Tibet",
  "Xinjiang"
 ],
 "French Indo-China": [
  "Cambodia",
  "Chinese warlords",
  "Cochin China",
  "Laos"
 ],
 "Dominican Republic": [
  "Haiti"
 ],
 "Haiti": [
  "Dominican Republic"
 ],
 "Costa Rica": [
  "Nicaragua",
  "Panama"
 ],
 "Nicaragua": [
  "Costa Rica",
  "Honduras"
 ],
 "Honduras": [
  "El Salvador",
  "Guatemala",
  "Nicaragua"
 ],
 "Cochin China": [
  "Cambodia",
  "French Indo-China"
 ],
 "Panama": [
  "Colombia",
  "Costa Rica"
 ],
 "French West Africa": [
  "Algeria (France)",
  "French Equatorial Africa",
  "Gambia, The",
  "Gold Coast",
  "Guinea-Bissau",
  "Liberia",
  "Libya",
  "Nigeria",
  "Rio De Oro",
  "Sierra Leone",
  "Spanish Sahara",
  "Togo"
 ],
 "Sierra Leone": [
  "French West Africa",
  "Liberia"
 ],
 "Liberia": [
  "French West Africa",
  "Sierra Leone"
 ],
 "Colombia": [
  "Brazil",
  "Ecuador",
  "Panama",
  "Peru",
  "Venezuela"
 ],
 "Brazil": [
  "Argentina",
  "Bolivia",
  "Colombia",
  "French Guiana",
  "Guyana",
  "Paraguay",
  "Peru",
  "Suriname",
  "Uruguay",
  "Venezuela"
 ],
 "Guyana": [
  "Brazil",
  "Suriname",
  "Venezuela"
 ],
 "Venezuela": [
  "Brazil",
  "Colombia",
  "Guyana"
 ],
 "Suriname": [
  "Brazil",
  "French Guiana",
  "Guyana"
 ],
 "Belgian Congo": [
  "Angola (Portugal)",
  "Burundi",
  "Congo (France)",
  "French Equatorial Africa",
  "Northern Rhodesia",
  "Rwanda (Belgium)",
  "Sudan",
  "Tanzania, United Republic of",
  "Uganda"
 ],
 "Congo (France)": [
  "Angola (Portugal)",
  "Belgian Congo",
  "French Cameroons",
  "French Equatorial Africa"
 ],
 "French Equatorial Africa": [
  "Belgian Congo",
  "Congo (France)",
  "Equatorial Guinea",
  "French Cameroons",
  "French West Africa",
  "Libya",
  "Nigeria",
  "Sudan"
 ],
 "Sudan": [
  "Belgian Congo",
  "Egypt",
  "Eritrea (Italy)",
  "Ethiopia (Italy)",
  "French Equatorial Africa",
  "Kenya",
  "Libya",
  "Uganda"
 ],
 "Uganda": [
  "Belgian Congo",
  "Kenya",
  "Rwanda (Belgium)",
  "Sudan",
  "Tanzania, United Republic of"
 ],
 "Rwanda (Belgium)": [
  "Belgian Congo",
  "Burundi",
  "Tanzania, United Republic of",
  "Uganda"
 ],
 "Burundi": [
  "Belgian Congo",
  "Rwanda (Belgium)",
  "Tanzania, United Republic of"
 ],
 "Tanzania, United Republic of": [
  "Belgian Congo",
  "Burundi",
  "Kenya",
  "Malawi",
  "Mozambique (Portugal)",
  "Northern Rhodesia",
  "Rwanda (Belgium)",
  "Uganda"
 ],
 "Northern Rhodesia": [
  "Angola (Portugal)",
  "Belgian Congo",
  "Botswana",
  "Malawi",
  "Mozambique (Portugal)",
  "Southern Rhodesia",
  "Tanzania, United Republic of",
  "Union of South Africa"
 ],
 "Angola (Portugal)": [
  "Belgian Congo",
  "Congo (France)",
  "Northern Rhodesia",
  "Union of South Africa"
 ],
 "Kenya": [
  "Ethiopia (Italy)",
  "Italian Somaliland",
  "Sudan",
  "Tanzania, United Republic of",
  "Uganda"
 ],
 "Mozambique (Portugal)": [
  "Malawi",
  "Northern Rhodesia",
  "Southern Rhodesia",
  "Swaziland",
  "Tanzania, United Republic of",
  "Union of South Africa"
 ],
 "Malawi": [
  "Mozambique (Portugal)",
  "Northern Rhodesia",
  "Tanzania, United Republic of"
 ],
 "Union of South Africa": [
  "Angola (Portugal)",
  "Botswana",
  "Lesotho",
  "Mozambique (Portugal)",
  "Northern Rhodesia",
  "Southern Rhodesia",
  "Swaziland",
  "Walbis Bay"
 ],
 "Southern Rhodesia": [
  "Botswana",
  "Mozambique (Portugal)",
  "Northern Rhodesia",
  "Union of South Africa"
 ],
 "Botswana": [
  "Northern Rhodesia",
  "Southern Rhodesia",
  "Union of South Africa"
 ],
 "Bolivia": [
  "Argentina",
  "Brazil",
  "Chile",
  "Paraguay",
  "Peru"
 ],
 "Peru": [
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador"
 ],
 "Paraguay": [
  "Argentina",
  "Bolivia",
  "Brazil"
 ],
 "Argentina": [
  "Bolivia",
  "Brazil",
  "Chile",
  "Paraguay",
  "Uruguay"
 ],
 "Chile": [
  "Argentina",
  "Bolivia",
  "Peru"
 ],
 "Swaziland": [
  "Mozambique (Portugal)",
  "Union of South Africa"
 ],
 "Lesotho": [
  "Union of South Africa"
 ],
 "Uruguay": [
  "Argentina",
  "Brazil"
 ],
 "Estonia": [
  "Latvia",
  "USSR"
 ],
 "USSR": [
  "Afghanistan",
  "Armenia",
  "Empire of Japan",
  "Estonia",
  "Finland",
  "Iran",
  "Latvia",
  "Mongolia",
  "Poland",
  "Romania",
  "Xinjiang"
 ],
 "Latvia": [
  "Estonia",
  "Lithuania",
  "Poland",
  "USSR"
 ],
 "Poland": [
  "Czechoslovakia",
  "Germany",
  "Latvia",
  "Lithuania",
  "Romania",
  "USSR"
 ],
 "Lithuania": [
  "Germany",
  "Latvia",
  "Poland"
 ],
 "Empire of Japan": [
  "Chinese warlords",
  "Mongolia",
  "USSR"
 ],
 "Mongolia": [
  "Chinese warlords",
  "Empire of Japan",
  "USSR",
  "Xinjiang"
 ],
 "Xinjiang": [
  "Afghanistan",
  "British Raj",
  "Chinese warlords",
  "Mongolia",
  "Tibet",
  "USSR"
 ],
 "Netherlands": [
  "Belgium",
  "Germany"
 ],
 "Albania": [
  "Greece",
  "Yugoslavia"
 ],
 "Yugoslavia": [
  "Albania",
  "Bulgaria",
  "Germany",
  "Greece",
  "Hungary",
  "Italy",
  "Romania"
 ],
 "Greece": [
  "Albania",
  "Bulgaria",
  "Turkey",
  "Yugoslavia"
 ],
 "Turkey": [
  "Armenia",
  "Bulgaria",
  "Greece",
  "Syria (France)"
 ],
 "Armenia": [
  "Iran",
  "Syria (France)",
  "Turkey",
  "USSR"
 ],
 "Syria (France)": [
  "Armenia",
  "Iran",
  "Israel",
  "Jordan",
  "Mandatory Palestine (GB)",
  "Mesopotamia (GB)",
  "Turkey"
 ],
 "Bulgaria": [
  "Greece",
  "Romania",
  "Turkey",
  "Yugoslavia"
 ],
 "Iran": [
  "Afghanistan",
  "Armenia",
  "British Raj",
  "Mesopotamia (GB)",
  "Syria (France)",
  "USSR"
 ],
 "Afghanistan": [
  "British Raj",
  "Iran",
  "USSR",
  "Xinjiang"
 ],
 "Mesopotamia (GB)": [
  "Emirate of Bin Shal'an",
  "Hejaz",
  "Iran",
  "Israel",
  "Jordan",
  "Kuwait",
  "Mandatory Palestine (GB)",
  "Saudi Arabia",
  "Syria (France)"
 ],
 "Jordan": [
  "Hejaz",
  "Israel",
  "Mandatory Palestine (GB)",
  "Mesopotamia (GB)",
  "Saudi Arabia",
  "Syria (France)"
 ],
 "Libya": [
  "Algeria (France)",
  "Egypt",
  "French Equatorial Africa",
  "French West Africa",
  "Sudan",
  "Tunisia"
 ],
 "Tunisia": [
  "Algeria (France)",
  "Libya"
 ],
 "Algeria (France)": [
  "French West Africa",
  "Libya",
  "Morocco (France)",
  "Spanish Sahara",
  "Tunisia"
 ],
 "Spanish Sahara": [
  "Algeria (France)",
  "French West Africa",
  "Morocco (France)",
  "Rio De Oro"
 ],
 "Morocco (France)": [
  "Algeria (France)",
  "Spanish Sahara"
 ],
 "Mexico": [
  "Belize",
  "Guatemala",
  "United States"
 ],
 "United States": [
  "Canada",
  "Mexico"
 ],
 "Belize": [
  "Guatemala",
  "Mexico"
 ],
 "Guatemala": [
  "Belize",
  "El Salvador",
  "Honduras",
  "Mexico"
 ],
 "Kuwait": [
  "Emirate of Bin Shal'an",
  "Mesopotamia (GB)",
  "Saudi Arabia"
 ],
 "Malaysia": [
  "Brunei",
  "Dutch East Indies",
  "Siam"
 ],
 "El Salvador": [
  "Guatemala",
  "Honduras"
 ],
 "Ecuador": [
  "Colombia",
  "Peru"
 ],
 "Gold Coast": [
  "French West Africa",
  "Togo"
 ],
 "Togo": [
  "French West Africa",
  "Gold Coast"
 ],
 "Dutch East Indies": [
  "Australia",
  "Malaysia"
 ],
 "Brunei": [
  "Malaysia"
 ],
 "French Guiana": [
  "Brazil",
  "Suriname"
 ],
 "Equatorial Guinea": [
  "French Cameroons",
  "French Equatorial Africa"
 ],
 "French Cameroons": [
  "Congo (France)",
  "Equatorial Guinea",
  "French Equatorial Africa",
  "Nigeria"
 ],
 "Nigeria": [
  "French Cameroons",
  "French Equatorial Africa",
  "French West Africa"
 ],
 "Israel": [
  "Egypt",
  "Jordan",
  "Mandatory Palestine (GB)",
  "Mesopotamia (GB)",
  "Syria (France)"
 ],
 "Mandatory Palestine (GB)": [
  "Egypt",
  "Israel",
  "Jordan",
  "Mesopotamia (GB)",
  "Syria (France)"
 ],
 "Hejaz": [
  "Emirate of Bin Shal'an",
  "Jordan",
  "Mesopotamia (GB)",
  "Saudi Arabia",
  "Yemen",
  "Yemen (UK)"
 ],
 "Egypt": [
  "Israel",
  "Libya",
  "Mandatory Palestine (GB)",
  "Sudan"
 ],
 "Nepal": [
  "British Raj",
  "Tibet"
 ],
 "Eritrea (Italy)": [
  "Ethiopia (Italy)",
  "French Somaliland",
  "Sudan"
 ],
 "Ethiopia (Italy)": [
  "British Somaliland",
  "Eritrea (Italy)",
  "French Somaliland",
  "Italian Somaliland",
  "Kenya",
  "Sudan"
 ],
 "French Somaliland": [
  "British Somaliland",
  "Eritrea (Italy)",
  "Ethiopia (Italy)"
 ],
 "British Somaliland": [
  "Ethiopia (Italy)",
  "French Somaliland",
  "Italian Somaliland"
 ],
 "Italian Somaliland": [
  "British Somaliland",
  "Ethiopia (Italy)",
  "Kenya"
 ],
 "Gambia, The": [
  "French West Africa"
 ],
 "Guinea-Bissau": [
  "French West Africa"
 ],
 "Australia": [
  "Dutch East Indies"
 ],
 "Norway": [
  "Finland",
  "Sweden"
 ],
 "Sweden": [
  "Finland",
  "Norway"
 ],
 "Finland": [
  "Norway",
  "Sweden",
  "USSR"
 ],
 "Romania": [
  "Bulgaria",
  "Czechoslovakia",
  "Hungary",
  "Poland",
  "USSR",
  "Yugoslavia"
 ],
 "Hungary": [
  "Czechoslovakia",
  "Germany",
  "Romania",
  "Yugoslavia"
 ],
 "Czechoslovakia": [
  "Germany",
  "Hungary",
  "Poland",
  "Romania"
 ],
 "Yemen": [
  "Emirate of Bin Shal'an",
  "Hejaz",
  "Muscat and Oman",
  "Oman (British Raj)",
  "Saudi Arabia",
  "Yemen (UK)"
 ],
 "Yemen (UK)": [
  "Emirate of Bin Shal'an",
  "Hejaz",
  "Muscat and Oman",
  "Oman (British Raj)",
  "Saudi Arabia",
  "Yemen"
 ],
 "Rio De Oro": [
  "French West Africa",
  "Spanish Sahara"
 ],
 "Walbis Bay": [
  "Union of South Africa"
 ],
 "Saint Barthelemy": [
  "Saint Martin"
 ],
 "Saint Martin": [
  "Saint Barthelemy"
 ],
 "Denmark": [
  "Germany"
 ],
 "Canada": [
  "Dominion of Newfoundland",
  "United States"
 ],
 "Dominion of Newfoundland": [
  "Canada"
 ],
 "Hail": [
  "Emirate of Bin Shal'an"
 ]
};
